output:
  path: "./packages"
  target_architectures: [ "amd64" ]

source_repositories:
  - source_url: "https://download.docker.com/linux/ubuntu"
    architectures: [ "amd64" ]
    distributions: [ "noble" ]
  - source_url: "https://developer.download.nvidia.com/compute/cuda/repos/"
    architectures: [ "x86_64" ]
    distributions:
      - distribution_path: "ubuntu2404/x86_64"
  - source_url: "https://snapshot.ubuntu.com/ubuntu/20251029T140000Z"
    architectures: [ "amd64" ]
    distributions: [ "noble", "noble-updates" ]

packages:
  # Nvidia
  - "libcudnn9-dev-cuda-12 (= 9.12.0.46-1)"
  - "libcudnn9-cuda-12 (= 9.12.0.46-1)"
  - "cuda-cudart-12-9"
  - "cuda-nvml-dev-12-9"
  - "cuda-toolkit-12-9"
  - "cuda-drivers-580 (= 580.95.05-0ubuntu1)"
  - "nvidia-container-toolkit (= 1.18.0-1)"
  - "nvidia-container-toolkit-base (= 1.18.0-1)"
  - "libnvidia-container-tools (= 1.18.0-1)"
  - "libnvidia-container1 (= 1.18.0-1)"
  - "libnpp-12-9"
  - "libcufft-12-9"
  - "libcublas-12-9"
  - "libcurand-12-9"
  - "cuda-nvrtc-12-9"
  - "cuda-cccl-12-9"
  - "cuda-nvrtc-dev-12-9"
  - "nvidia-driver-580 (= 580.95.05-0ubuntu1)"
  # Ubuntu
  - "build-essential"
  - "linux-image-generic"
  - "linux-headers-generic"
  - "wget"
  - "curl"
  - "git"
  - "bash"
  - "dash"
  - "ncdu"
  - "podman"
  - "slirp4netns"
  - "buildah"
  - "ncurses-term"
  - "build-essential"
  - "software-properties-common"
  - "gstreamer1.0-alsa"
  - "gstreamer1.0-clutter-3.0"
  - "gstreamer1.0-gl"
  - "gstreamer1.0-gtk3"
  - "gstreamer1.0-libav"
  - "gstreamer1.0-packagekit"
  - "gstreamer1.0-pipewire"
  - "gstreamer1.0-plugins-bad"
  - "gstreamer1.0-plugins-base"
  - "gstreamer1.0-plugins-base-apps"
  - "gstreamer1.0-plugins-good"
  - "gstreamer1.0-plugins-ugly"
  - "gstreamer1.0-pulseaudio"
  - "gstreamer1.0-qt5"
  - "gstreamer1.0-rtsp"
  - "gstreamer1.0-tools"
  - "gstreamer1.0-x"
  - "libcairo2"
  - "libcairo2-dev"
  - "libboost-dev"
  - "libegl1-mesa-dev"
  - "libgl1-mesa-dev"
  - "libgles2"
  - "libgles2-mesa-dev"
  - "libglvnd-dev"
  - "libgstreamer-gl1.0-0"
  - "libgstreamer-opencv1.0-0"
  - "libgstreamer-plugins-bad1.0-0"
  - "libgstreamer-plugins-bad1.0-dev"
  - "libgstreamer-plugins-base1.0-0"
  - "libgstreamer-plugins-base1.0-dev"
  - "libgstreamer-plugins-good1.0-0"
  - "libgstreamer-plugins-good1.0-dev"
  - "libgstreamer1.0-0"
  - "libgstreamer1.0-dev"
  - "libgstrtspserver-1.0-0"
  - "libgstrtspserver-1.0-dev"
  - "libssl3t64"
  - "libssl-dev"
  - "rsync"
  - "sshfs"
  - "uuid-dev"
  - "libicu74"
  - "libnss3"
  - "ocl-icd-libopencl1"
  - "libblas3"
  - "liblapack3"
  - "gsettings-desktop-schemas"
  - "libglib2.0-bin"
  - "libglib2.0-0t64"
  - "fonts-dejavu"
  - "fontconfig"
  - "libyaml-cpp0.8"
  - "libpgm-5.3-0t64"
  - "gdb"
  - "libc-bin"
  - "valgrind"
  - "heaptrack"
  - "gzip"
  - "libjemalloc2"
  - "libjemalloc-dev"
  - "libgoogle-perftools-dev"
  - "lldb"
  - "gdbserver"
  - "gstreamer1.0-nice"
  - "dnsutils"
  - "coreutils"
  - "net-tools"
  - "iproute2"
  - "iputils-arping"
  - "iputils-clockdiff"
  - "iputils-ping"
  - "iputils-tracepath"
  - "traceroute"
  - "docker-ce"
  - "docker-ce-cli"
  - "containerd.io (>= 1.7.27-1)"
  - "docker-buildx-plugin"
  - "docker-compose-plugin"
  - "unzip"
  - "apt-transport-https"
  - "ca-certificates"
  - "gnupg"
  - "lsb-release"
  - "iptables"
  - "socat"
  - "ebtables"
  - "ethtool"
  - "nfs-common"
  - "bash-completion"
  - "jq"
  - "lvm2"
  - "thin-provisioning-tools"
  - "util-linux"
  - "udev"
  - "e2fsprogs"
  - "xfsprogs"
  - "btrfs-progs"
  - "ceph-common"
  - "hdparm"
  - "nvme-cli"
  - "nfs-common"
  - "open-iscsi"
  - "sg3-utils"
  - "nmap"
  - "conntrack"
  - "mtr"
  - "htop"
  - "iotop"
  - "iftop"
  - "sysstat"
  - "nvme-cli"
  - "smartmontools"
  - "tar"
  - "tmux"
  - "screen"
  - "strace"
  - "silversearcher-ag"
  - "tree"
  - "httpie"
  - "xz-utils"
  - "zlib1g"
  - "libarchive13t64"
  - "libdeflate0"
  - "gzip"
  - "fuse-overlayfs"
  - "ubuntu-server"
  - "libcurl4t64"
  - "etcd-client"